spring.application.name=deal_service
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

services.notification.url=${NOTIFICATION_URL}

logging.file.name=logs/deal-service.log
logging.level.com.practika.deal_service=DEBUG